behat:
    image: krzystof/the-wharves-behat
    volumes:
        - .:/var/work
    links:
        - hub
    environment:
        APP_ENV: acceptance

hub:
    image: qualiboo/testing-hub
    ports:
    - 4444:4444

firefox:
    image: qualiboo/testing-node-firefox
    ports:
    - 5900
    links:
    - hub
    environment:
        REMOTE_HOST_PARAM: "-maxSession 3 -browser browserName=firefox,maxInstances=3"

chrome:
    image: qualiboo/testing-node-chrome
    ports:
    - 5900
    links:
    - hub
