code:
    image: code
    volumes:
        - .:/code

php:
    image: php:7.0
    expose:
      - "9000"
    volumes_from:
      - code

web:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - php
    volumes_from:
      - code

db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  volumes_from:
    - code
